#include <exception>

#include "runner.hpp"
#include "frontend.hpp"
#include "main.hpp"

#if BUILD_FOR_RASPI
#include "Raspi-Port/Menu.hpp"
#endif

int main(int argc, char** argv) {
    std::vector<std::string> fileLines;

    #if BUILD_FOR_RASPI
    while(true) {
        std::string path = run_menu();
        read_file((char*)path.c_str(), fileLines);
        run_squiggly(fileLines);

        //TODO: print any error messages generated by run_squiggly
    }

    return 0;
    #else
    return parse_args(argc, argv, fileLines) || run_squiggly(fileLines);
    #endif
}